//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Quotations = new HashSet<Quotation>();
            this.Customers = new HashSet<Customer>();
            this.Expenses = new HashSet<Expense>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int CityID { get; set; }
    
        public virtual ICollection<Quotation> Quotations { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
    }
}
