//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Quotations = new HashSet<Quotation>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerMidName { get; set; }
        public string CustomerLastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int CityID { get; set; }
        public string Pin { get; set; }
        public int CustomerTypeID { get; set; }
        public int BranchID { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual City City { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual ICollection<Quotation> Quotations { get; set; }
    }
}
