//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseID { get; set; }
        public string ExpenseName { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ExpenseDate { get; set; }
        public string Description { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentModeNo { get; set; }
        public string Attachment_Url { get; set; }
        public int BranchID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
