//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public Quotation()
        {
            this.QuotationDetails = new HashSet<QuotationDetail>();
        }
    
        public int QuotationID { get; set; }
        public string QuotationNo { get; set; }
        public string QuotationSubjectLine { get; set; }
        public int CustomerTypeID { get; set; }
        public int QuotationServiceTypeID { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public bool IsSent { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual QuotationServiceMaster QuotationServiceMaster { get; set; }
        public virtual ICollection<QuotationDetail> QuotationDetails { get; set; }
    }
}
