//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDetail
    {
        public int ItemID { get; set; }
        public int QuotationID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> TankQuantity { get; set; }
        public Nullable<decimal> TankVolume { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsSent { get; set; }
    
        public virtual Quotation Quotation { get; set; }
    }
}
