//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationServiceType
    {
        public QuotationServiceType()
        {
            this.Quotations = new HashSet<Quotation>();
        }
    
        public int ServiceTypeID { get; set; }
        public string ServiceTypeName { get; set; }
        public string ShortCode { get; set; }
    
        public virtual ICollection<Quotation> Quotations { get; set; }
    }
}
