//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_Details
    {
        public Quotation_Details()
        {
            this.Quotation_Item_Details = new HashSet<Quotation_Item_Details>();
        }
    
        public int Quotation_ID { get; set; }
        public string Quotation_No { get; set; }
        public string Quotation_Subject_Line { get; set; }
        public int Customer_Type_ID { get; set; }
        public int Quotation_Service_Type_ID { get; set; }
        public string Contact_Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public int Branch_ID { get; set; }
    
        public virtual QuotationServiceMaster QuotationServiceMaster { get; set; }
        public virtual ICollection<Quotation_Item_Details> Quotation_Item_Details { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
    }
}
