//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_Item_Details
    {
        public int Item_ID { get; set; }
        public int Quotation_ID { get; set; }
        public string Item_Description { get; set; }
        public Nullable<int> Tank_Quantity { get; set; }
        public Nullable<decimal> Tank_Volume { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
    
        public virtual Quotation_Details Quotation_Details { get; set; }
    }
}
