//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationServiceMaster
    {
        public QuotationServiceMaster()
        {
            this.Quotation_Details = new HashSet<Quotation_Details>();
        }
    
        public int Service_Type_ID { get; set; }
        public string Service_Type_Name { get; set; }
    
        public virtual ICollection<Quotation_Details> Quotation_Details { get; set; }
    }
}
